### ISSUE TITLE
Не хватает метода andFilterDateBetween

### ISSUE THREAD

**Issue by s1lver** [pozitronik/yii2-traits#2]
Предлагаю добавить метод `andFilterDateBetween` в ActiveQueryTrait.php.

Это - часто востребованная функциональность которая копируются из проекта в проект, а в некоторых случаях  изобретается заново

**Comment by pozitronik** [comment]
> Предлагаю добавить метод `andFilterDateBetween` в ActiveQueryTrait.php.
> 
> Это - часто востребованная функциональность которая копируются из проекта в проект, а в некоторых случаях изобретается заново

https://github.com/pozitronik/yii2-traits/blob/master/src/models/ActiveQuery.php

**Comment by s1lver** [comment]
Я думал в trait. Ну ладно

**Comment by pozitronik** [comment]
> Я думал в trait. Ну ладно

Я не помню, почему, но так пришлось сделать.
